apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  namespaces: "my-argocd,my-echo-0,my-echo-1,my-echo-2,my-echo-3,my-echo-4,my-echo-5,my-echo-6"
  config: "{}"
type: Opaque
