apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: echo
              mountPath: /etc/echo
            - name: echo-secret
              mountPath: /etc/echo-secret
      volumes:
        - name: echo
          configMap:
            name: echo
        - name: echo-secret
          secret:
            secretName: echo
